# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/protobufs/tests/simple_service/another_action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/protobufs/tests/simple_service/another_action.proto',
  package='another_action',
  serialized_pb=_b('\n;service/protobufs/tests/simple_service/another_action.proto\x12\x0e\x61nother_action\"_\n\x07Request\x12\x0c\n\x04test\x18\x01 \x01(\t\x12.\n\x06nested\x18\x02 \x01(\x0b\x32\x1e.another_action.Request.Nested\x1a\x16\n\x06Nested\x12\x0c\n\x04\x65\x63ho\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST_NESTED = _descriptor.Descriptor(
  name='Nested',
  full_name='another_action.Request.Nested',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='echo', full_name='another_action.Request.Nested.echo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=174,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='another_action.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test', full_name='another_action.Request.test', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nested', full_name='another_action.Request.nested', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_NESTED, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=174,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='another_action.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='another_action.Response.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=202,
)

_REQUEST_NESTED.containing_type = _REQUEST
_REQUEST.fields_by_name['nested'].message_type = _REQUEST_NESTED
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(

  Nested = _reflection.GeneratedProtocolMessageType('Nested', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_NESTED,
    __module__ = 'service.protobufs.tests.simple_service.another_action_pb2'
    # @@protoc_insertion_point(class_scope:another_action.Request.Nested)
    ))
  ,
  DESCRIPTOR = _REQUEST,
  __module__ = 'service.protobufs.tests.simple_service.another_action_pb2'
  # @@protoc_insertion_point(class_scope:another_action.Request)
  ))
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.Nested)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'service.protobufs.tests.simple_service.another_action_pb2'
  # @@protoc_insertion_point(class_scope:another_action.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
