# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/protobufs/tests/simple_service/exception_action.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/protobufs/tests/simple_service/exception_action.proto',
  package='exception_action',
  syntax='proto2',
  serialized_pb=b'\n=service/protobufs/tests/simple_service/exception_action.proto\x12\x10\x65xception_action\":\n\x07Request\x12/\n\nerror_type\x18\x01 \x01(\x0e\x32\x1b.exception_action.ErrorType\"\n\n\x08Response*\x8b\x01\n\tErrorType\x12\x0f\n\x0bVALUE_ERROR\x10\x01\x12\x10\n\x0c\x43USTOM_ERROR\x10\x02\x12\x10\n\x0c\x41\x43TION_ERROR\x10\x03\x12\x1d\n\x19\x41\x43TION_ERROR_WITH_DETAILS\x10\x04\x12\x16\n\x12\x41\x43TION_FIELD_ERROR\x10\x05\x12\x12\n\x0eUNMAPPED_ERROR\x10\x06'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ERRORTYPE = _descriptor.EnumDescriptor(
  name='ErrorType',
  full_name='exception_action.ErrorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VALUE_ERROR', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM_ERROR', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_ERROR', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_ERROR_WITH_DETAILS', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_FIELD_ERROR', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNMAPPED_ERROR', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=156,
  serialized_end=295,
)
_sym_db.RegisterEnumDescriptor(_ERRORTYPE)

ErrorType = enum_type_wrapper.EnumTypeWrapper(_ERRORTYPE)
VALUE_ERROR = 1
CUSTOM_ERROR = 2
ACTION_ERROR = 3
ACTION_ERROR_WITH_DETAILS = 4
ACTION_FIELD_ERROR = 5
UNMAPPED_ERROR = 6



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='exception_action.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_type', full_name='exception_action.Request.error_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=141,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='exception_action.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=153,
)

_REQUEST.fields_by_name['error_type'].enum_type = _ERRORTYPE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['ErrorType'] = _ERRORTYPE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'service.protobufs.tests.simple_service.exception_action_pb2'
  # @@protoc_insertion_point(class_scope:exception_action.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'service.protobufs.tests.simple_service.exception_action_pb2'
  # @@protoc_insertion_point(class_scope:exception_action.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
