# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/protobufs/tests/simple_service/required_fields_action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/protobufs/tests/simple_service/required_fields_action.proto',
  package='required_fields_action',
  serialized_pb=_b('\nCservice/protobufs/tests/simple_service/required_fields_action.proto\x12\x16required_fields_action\"?\n\rTestContainer\x12\x16\n\x0erequired_field\x18\x01 \x01(\t\x12\x16\n\x0eoptional_field\x18\x02 \x01(\t\"\x9d\x01\n\x07Request\x12\x16\n\x0erequired_field\x18\x01 \x01(\t\x12\x16\n\x0eoptional_field\x18\x02 \x01(\t\x12\x1f\n\x17required_repeated_field\x18\x03 \x03(\t\x12\x41\n\x12required_container\x18\x04 \x01(\x0b\x32%.required_fields_action.TestContainer\"\x9e\x01\n\x08Response\x12\x16\n\x0erequired_field\x18\x01 \x01(\t\x12\x16\n\x0eoptional_field\x18\x02 \x01(\t\x12\x1f\n\x17required_repeated_field\x18\x03 \x03(\t\x12\x41\n\x12required_container\x18\x04 \x01(\x0b\x32%.required_fields_action.TestContainer')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TESTCONTAINER = _descriptor.Descriptor(
  name='TestContainer',
  full_name='required_fields_action.TestContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='required_field', full_name='required_fields_action.TestContainer.required_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optional_field', full_name='required_fields_action.TestContainer.optional_field', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=158,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='required_fields_action.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='required_field', full_name='required_fields_action.Request.required_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optional_field', full_name='required_fields_action.Request.optional_field', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='required_repeated_field', full_name='required_fields_action.Request.required_repeated_field', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='required_container', full_name='required_fields_action.Request.required_container', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=318,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='required_fields_action.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='required_field', full_name='required_fields_action.Response.required_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optional_field', full_name='required_fields_action.Response.optional_field', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='required_repeated_field', full_name='required_fields_action.Response.required_repeated_field', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='required_container', full_name='required_fields_action.Response.required_container', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=479,
)

_REQUEST.fields_by_name['required_container'].message_type = _TESTCONTAINER
_RESPONSE.fields_by_name['required_container'].message_type = _TESTCONTAINER
DESCRIPTOR.message_types_by_name['TestContainer'] = _TESTCONTAINER
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

TestContainer = _reflection.GeneratedProtocolMessageType('TestContainer', (_message.Message,), dict(
  DESCRIPTOR = _TESTCONTAINER,
  __module__ = 'service.protobufs.tests.simple_service.required_fields_action_pb2'
  # @@protoc_insertion_point(class_scope:required_fields_action.TestContainer)
  ))
_sym_db.RegisterMessage(TestContainer)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'service.protobufs.tests.simple_service.required_fields_action_pb2'
  # @@protoc_insertion_point(class_scope:required_fields_action.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'service.protobufs.tests.simple_service.required_fields_action_pb2'
  # @@protoc_insertion_point(class_scope:required_fields_action.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
