# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/protobufs/tests/response_registry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import service.protobufs.common.soa_pb2
import service.protobufs.tests.simple_service.another_action_pb2
import service.protobufs.tests.simple_service.simple_action_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/protobufs/tests/response_registry.proto',
  package='tests.response.registry',
  serialized_pb=_b('\n/service/protobufs/tests/response_registry.proto\x12\x17tests.response.registry\x1a\"service/protobufs/common/soa.proto\x1a;service/protobufs/tests/simple_service/another_action.proto\x1a:service/protobufs/tests/simple_service/simple_action.proto\"\xa7\x01\n\rSimpleService2K\n\x0e\x61nother_action\x12\x19.soa.ActionResponseResult\x18\x65 \x01(\x0b\x32\x18.another_action.Response2I\n\rsimple_action\x12\x19.soa.ActionResponseResult\x18\x66 \x01(\x0b\x32\x17.simple_action.Response')
  ,
  dependencies=[service.protobufs.common.soa_pb2.DESCRIPTOR,service.protobufs.tests.simple_service.another_action_pb2.DESCRIPTOR,service.protobufs.tests.simple_service.simple_action_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIMPLESERVICE = _descriptor.Descriptor(
  name='SimpleService',
  full_name='tests.response.registry.SimpleService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='another_action', full_name='tests.response.registry.SimpleService.another_action', index=0,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='simple_action', full_name='tests.response.registry.SimpleService.simple_action', index=1,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=401,
)

DESCRIPTOR.message_types_by_name['SimpleService'] = _SIMPLESERVICE

SimpleService = _reflection.GeneratedProtocolMessageType('SimpleService', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLESERVICE,
  __module__ = 'service.protobufs.tests.response_registry_pb2'
  # @@protoc_insertion_point(class_scope:tests.response.registry.SimpleService)
  ))
_sym_db.RegisterMessage(SimpleService)

_SIMPLESERVICE.extensions_by_name['another_action'].message_type = service.protobufs.tests.simple_service.another_action_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_SIMPLESERVICE.extensions_by_name['another_action'])
_SIMPLESERVICE.extensions_by_name['simple_action'].message_type = service.protobufs.tests.simple_service.simple_action_pb2._RESPONSE
service.protobufs.common.soa_pb2.ActionResponseResult.RegisterExtension(_SIMPLESERVICE.extensions_by_name['simple_action'])

# @@protoc_insertion_point(module_scope)
