DEFAULT_TRANSPORT = 'service.transports.local.instance'
DEFAULT_METRICS_HANDLER = 'service.metrics.base.instance'

METRICS_ENABLED = True
PROTOBUF_REQUEST_REGISTRY = None
PROTOBUF_RESPONSE_REGISTRY = None

DEFAULT_PAGE_SIZE = 15
MAX_PAGE_SIZE = 100
