# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from service.protobufs.generated import soa_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple_action.proto',
  package='test.protobufs',
  serialized_pb=_b('\n\x13simple_action.proto\x12\x0etest.protobufs\x1a\tsoa.proto\"1\n\x07Request2&\n\x04\x65\x63ho\x12\x18.soa.ActionRequestParams\x18\x65 \x01(\t\"5\n\x08Response2)\n\x06\x61nswer\x12\x19.soa.ActionResponseResult\x18\x65 \x01(\t')
  ,
  dependencies=[soa_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='test.protobufs.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='echo', full_name='test.protobufs.Request.echo', index=0,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=99,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='test.protobufs.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='test.protobufs.Response.answer', index=0,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'simple_action_pb2'
  # @@protoc_insertion_point(class_scope:test.protobufs.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'simple_action_pb2'
  # @@protoc_insertion_point(class_scope:test.protobufs.Response)
  ))
_sym_db.RegisterMessage(Response)

soa_pb2.ActionRequestParams.RegisterExtension(_REQUEST.extensions_by_name['echo'])
soa_pb2.ActionResponseResult.RegisterExtension(_RESPONSE.extensions_by_name['answer'])

# @@protoc_insertion_point(module_scope)
