# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/protobufs/tests/registry/responses.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import service_protobufs.soa_pb2
import service.protobufs.tests.simple_service.another_action_pb2
import service.protobufs.tests.simple_service.exception_action_pb2
import service.protobufs.tests.simple_service.paginated_action_pb2
import service.protobufs.tests.simple_service.required_fields_action_pb2
import service.protobufs.tests.simple_service.simple_action_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service/protobufs/tests/registry/responses.proto',
  package='tests.registry.responses',
  serialized_pb=_b('\n0service/protobufs/tests/registry/responses.proto\x12\x18tests.registry.responses\x1a\x1bservice_protobufs/soa.proto\x1a;service/protobufs/tests/simple_service/another_action.proto\x1a=service/protobufs/tests/simple_service/exception_action.proto\x1a=service/protobufs/tests/simple_service/paginated_action.proto\x1a\x43service/protobufs/tests/simple_service/required_fields_action.proto\x1a:service/protobufs/tests/simple_service/simple_action.proto\"\x81\x03\n\x06Simple2E\n\x0e\x61nother_action\x12\x13.soa.ActionResultV1\x18\x65 \x01(\x0b\x32\x18.another_action.Response2C\n\rsimple_action\x12\x13.soa.ActionResultV1\x18\x66 \x01(\x0b\x32\x17.simple_action.Response2I\n\x10paginated_action\x12\x13.soa.ActionResultV1\x18g \x01(\x0b\x32\x1a.paginated_action.Response2I\n\x10\x65xception_action\x12\x13.soa.ActionResultV1\x18h \x01(\x0b\x32\x1a.exception_action.Response2U\n\x16required_fields_action\x12\x13.soa.ActionResultV1\x18i \x01(\x0b\x32 .required_fields_action.Response')
  ,
  dependencies=[service_protobufs.soa_pb2.DESCRIPTOR,service.protobufs.tests.simple_service.another_action_pb2.DESCRIPTOR,service.protobufs.tests.simple_service.exception_action_pb2.DESCRIPTOR,service.protobufs.tests.simple_service.paginated_action_pb2.DESCRIPTOR,service.protobufs.tests.simple_service.required_fields_action_pb2.DESCRIPTOR,service.protobufs.tests.simple_service.simple_action_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIMPLE = _descriptor.Descriptor(
  name='Simple',
  full_name='tests.registry.responses.Simple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='another_action', full_name='tests.registry.responses.Simple.another_action', index=0,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='simple_action', full_name='tests.registry.responses.Simple.simple_action', index=1,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paginated_action', full_name='tests.registry.responses.Simple.paginated_action', index=2,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exception_action', full_name='tests.registry.responses.Simple.exception_action', index=3,
      number=104, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='required_fields_action', full_name='tests.registry.responses.Simple.required_fields_action', index=4,
      number=105, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=809,
)

DESCRIPTOR.message_types_by_name['Simple'] = _SIMPLE

Simple = _reflection.GeneratedProtocolMessageType('Simple', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLE,
  __module__ = 'service.protobufs.tests.registry.responses_pb2'
  # @@protoc_insertion_point(class_scope:tests.registry.responses.Simple)
  ))
_sym_db.RegisterMessage(Simple)

_SIMPLE.extensions_by_name['another_action'].message_type = service.protobufs.tests.simple_service.another_action_pb2._RESPONSE
service_protobufs.soa_pb2.ActionResultV1.RegisterExtension(_SIMPLE.extensions_by_name['another_action'])
_SIMPLE.extensions_by_name['simple_action'].message_type = service.protobufs.tests.simple_service.simple_action_pb2._RESPONSE
service_protobufs.soa_pb2.ActionResultV1.RegisterExtension(_SIMPLE.extensions_by_name['simple_action'])
_SIMPLE.extensions_by_name['paginated_action'].message_type = service.protobufs.tests.simple_service.paginated_action_pb2._RESPONSE
service_protobufs.soa_pb2.ActionResultV1.RegisterExtension(_SIMPLE.extensions_by_name['paginated_action'])
_SIMPLE.extensions_by_name['exception_action'].message_type = service.protobufs.tests.simple_service.exception_action_pb2._RESPONSE
service_protobufs.soa_pb2.ActionResultV1.RegisterExtension(_SIMPLE.extensions_by_name['exception_action'])
_SIMPLE.extensions_by_name['required_fields_action'].message_type = service.protobufs.tests.simple_service.required_fields_action_pb2._RESPONSE
service_protobufs.soa_pb2.ActionResultV1.RegisterExtension(_SIMPLE.extensions_by_name['required_fields_action'])

# @@protoc_insertion_point(module_scope)
